version: '3'
services:
  db:
    container_name: desafio-vaga-db
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - 5440:5432
    environment:
      - POSTGRESQL_USERNAME=postgresql
      - POSTGRESQL_PASSWORD=desafio
      - POSTGRESQL_DATABASE=desafio-vagadb